#!/bin/bash
#=====================================================================#
#                                                                     #
#        _               _           _                                #
#       (_)             | |         (_)                               #
#  _ __  ___  ____ _  __| |_ __ ___  _ _ __  ___                      #
# | '_ \| \ \/ / _` |/ _` | '_ ` _ \| | '_ \/ __|                     #
# | | | | |>  < (_| | (_| | | | | | | | | | \__ \                     #
# |_| |_|_/_/\_\__,_|\__,_|_| |_| |_|_|_| |_|___/                     #
#                                                                     #
#                                                                     #
#                                                                     #
#=====================================================================#

# -------------------------
# [ENVIRONMENTAL VARIABLES]
# -------------------------
export EDITOR=nvim

# -------------------------
# [ALIAS]
# -------------------------

alias vim="nvim"
alias emacs="/usr/bin/emacs -nw"
alias ls="ls -CF --color=auto"
alias ps="ps auxf"
alias grep="grep --color=auto"
#alias dotfiles='/usr/bin/git --git-dir=/home/mahellma/.dotfiles/ --work-tree=/home/mahellma'
alias dotfiles="~/github/dotfiles/env_run.sh"
alias python='python3'
alias ll='ls -lh'
alias la='ls -A'
alias l='ls -CF'
alias lll='ls -lha'

# -------------------------
# [SCRIPTS]
# -------------------------
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

# -------------------------
# [COMPUTER]
# -------------------------

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Make colorcoding available for everyone
Black='\e[0;30m'        # Black
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green
Yellow='\e[0;33m'       # Yellow
Blue='\e[0;34m'         # Blue
Purple='\e[0;35m'       # Purple
Cyan='\e[0;36m'         # Cyan
White='\e[0;37m'        # White

# Bold
BBlack='\e[1;30m'       # Black
BRed='\e[1;31m'         # Red
BGreen='\e[1;32m'       # Green
BYellow='\e[1;33m'      # Yellow
BBlue='\e[1;34m'        # Blue
BPurple='\e[1;35m'      # Purple
BCyan='\e[1;36m'        # Cyan
BWhite='\e[1;37m'       # White

# Background
On_Black='\e[40m'       # Black
On_Red='\e[41m'         # Red
On_Green='\e[42m'       # Green
On_Yellow='\e[43m'      # Yellow
On_Blue='\e[44m'        # Blue
On_Purple='\e[45m'      # Purple
On_Cyan='\e[46m'        # Cyan
On_White='\e[47m'       # White

NC="\e[m"               # Color Reset

# New alert text
ALERT=${BWhite}${On_Red} # Bold White on red background



# Set the prompt
export PS1='\[\033[38;5;12m\][\[$(tput sgr0)\]\[\033[38;5;10m\]\u\[$(tput sgr0)\]\[\033[38;5;12m\]@\[$(tput sgr0)\]\[\033[38;5;7m\]\h\[$(tput sgr0)\]\[\033[38;5;12m\]]\[$(tput sgr0)\]\[\033[38;5;15m\]: \[$(tput sgr0)\]\[\033[38;5;7m\]\w\[$(tput sgr0)\]\[\033[38;5;12m\]>\[$(tput sgr0)\]\[\033[38;5;10m\]\\$\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\] '
[ -e "/etc/DIR_COLORS" ] && DIR_COLORS="/etc/DIR_COLORS"
[ -e "$HOME/.dircolors" ] && DIR_COLORS="$HOME/.dircolors"
[ -e "$DIR_COLORS" ] || DIR_COLORS=""
eval "`dircolors -b $DIR_COLORS`"

# Write the message of the day
# motd
export SSH_AUTH_SOCK=/home/mahellma/.bitwarden-ssh-agent.sock
